### ISSUE TITLE
python conda example

### ISSUE THREAD

**Issue by jonocodes** [flox/floxenvs#258]
Would love a conda example.
There are a bunch of conda options in Nix - and they all work differently. So anything will do.
One of the troubles with conda is it prefers to take over the shell - so people deal with that in different ways. Maybe this is one of them
https://mynixos.com/nixpkgs/package/python311Packages.conda-inject

Thanks.

🎩

**Comment by garbas** [comment]
Using `conda-inject` is a great idea, I haven't heard of it before. I imagine mangling with `PYTHONPATH` (aka `sys.path`) can likely cause some weird problems, but it might be just what will work for some. 

But if my memory serving me right, `conda` expect a FHS like layout. That is why with Nix you would use [`conda-shell`](https://github.com/NixOS/nixpkgs/blob/d7c75f075f014ea12e637644c2c5da188953ad9f/pkgs/by-name/co/conda/package.nix#L99).

Do you have an example `conda` projects I can play and see if I can get it to work?

**Comment by jonocodes** [comment]
I've never used conda-inject myself. I just saw it in the nix repos.

I have managed to get conda working, using the "conda" package - which you mentioned above, provides conda-shell. But there are several other like packages (mamba, micromamba) which I have not tried lately.

My project uses npm, conda, pdm.

I was hoping to create and initialize the conda environment during activation. But instead I have had to manually install conda. Then use conda-shell to initialize the conda environment. Then I can start flox which will the activate the environment at start.

Here is most of my manifest.toml

``` toml
[install]
yarn = { pkg-path = "yarn", version = "1.22.22" }
node-gyp.pkg-path = "node-gyp"  # needed for cdktf-cli
node-gyp.pkg-group = "node-gyp"
python3 = { pkg-path = "python311" }
go.pkg-path = "go"
gcc.pkg-path = "gcc"
kubectl.pkg-path = "kubectl"
zlib.pkg-path = "zlib"
binutils.pkg-path = "binutils"
terraform.pkg-path = "terraform"
gnumake.pkg-path = "gnumake"
conda.pkg-path = "conda"
conda.systems = ["aarch64-linux", "x86_64-linux"]
nodejs_18.pkg-path = "nodejs_18"

[hook]
on-activate = '''
# conda-shell stuff should happen here to create the environment?
'''

[profile]
fish = '''

  echo "Activating conda environment" >&2
  eval /home/jono/.conda/bin/conda "shell.fish" "hook" $argv | source

  conda activate my-env
  pip install pdm --quiet

  if test ! -d "$FLOX_ENV_PROJECT/node_modules"
    yarn
  end

'''

```
